version: '3.8'

services:
  # Main application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: cicd-orchestrator
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Application
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - HOST=0.0.0.0
      - PORT=8000
      
      # GitLab
      - GITLAB_API_TOKEN=${GITLAB_API_TOKEN}
      - GITLAB_BASE_URL=${GITLAB_BASE_URL:-https://gitlab.com}
      - GITLAB_WEBHOOK_SECRET=${GITLAB_WEBHOOK_SECRET}
      
      # AI Providers
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEFAULT_AI_PROVIDER=${DEFAULT_AI_PROVIDER:-openai}
      
      # Database (Oracle)
      - DATABASE_URL=${DATABASE_URL}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=json
      
      # Monitoring
      - SENTRY_DSN=${SENTRY_DSN}
    # Removed postgres dependency since using external Oracle DB
    # depends_on:
    #   - postgres
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cicd-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: cicd-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - cicd-network
    profiles:
      - nginx

# Define volumes (postgres_data commented out since using external Oracle DB)
# volumes:
#   postgres_data:
#     driver: local

# Define networks
networks:
  cicd-network:
    driver: bridge
